<style>
  body {
    margin-top: 3rem;
  }

  i {
    font-size: 18px;
  }

  .color-change-2x {
    -webkit-animation: color-change-2x 2s linear infinite alternate both;
    animation: color-change-2x 2s linear infinite alternate both
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-9-17 22:37:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  @-webkit-keyframes color-change-2x {
    0% {
      background: #19dcea
    }

    100% {
      background: #b22cff
    }
  }

  @keyframes color-change-2x {
    0% {
      background: #19dcea
    }

    100% {
      background: #b22cff
    }
  }

  /* animasi text judul */
  .tracking-in-contract {
    animation: tracking-in-contract 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-9-17 23:21:41
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation tracking-in-contract
 * ----------------------------------------
 */
  @keyframes tracking-in-contract {
    0% {
      letter-spacing: 1em;
      opacity: 0;
    }

    40% {
      opacity: 0.6;
    }

    100% {
      letter-spacing: normal;
      opacity: 1;
    }
  }

  /* mobile */
  .judul {
    font-size: 24px;
  }


  /* clock */
  #clock {
    color: white;
    font-size: 11px;
    margin-left: auto;
    margin-right: 5px;
  }


  /* desctop */

  @media (min-width: 992px) {
    .icondesc {
      font-size: 25px;
    }

    .judul {
      font-size: 30px;
    }


    #clock {
      font-size: 20px;
    }


  }
</style>